### ISSUE TITLE
`wait_ready` will never work when the ready condition is `true`

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/integration-test-commons#16]
I'm not sure if this is intentional for some reason but the method can only end successfully if the ready condition stays false.

That seems wrong to me.
Shouldn't this _only_ ever return when the condition turns `true` **and** all pods exist?

https://github.com/stackabletech/integration-test-commons/blob/b1099206ac40d4f7e3ed2b992be797d22ad033f3/src/operator/setup.rs#L126-L166

**Comment by razvan** [comment]
Notes after looking into this:
* Operators seem to leave fresh new clusters in a "dangling" `type: "Updating"` condition with `status: False` . Probably that's where the code above is coming from and also the reason it works (for now).
* It's probably best to ignore this field for now and just use the `Pod` readiness state.
* An article about the history, meaning and usefulness of conditions: https://maelvls.dev/kubernetes-conditions/.
